import { CalendarCheck, LockKeyhole, Mail } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'

export function Login() {
  const { login } = useAuth()
  const navigate = useNavigate()
  const [role, setRole] = useState<'Admin' | 'Teacher'>('Admin')
  const [email, setEmail] = useState('admin@atrio.com')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setSubmitting(true); try { await login({ email, password }, role); navigate('/') } catch { setError('Unable to sign in. Check your email, password, and API connection.') } finally { setSubmitting(false) } }
  return <div className="grid min-h-screen bg-[radial-gradient(circle_at_top_left,_#3730a3,_transparent_30%),#0f172a] lg:grid-cols-2"><div className="hidden flex-col justify-between p-12 lg:flex"><div className="flex items-center gap-3"><div className="rounded-xl bg-indigo-500 p-2"><CalendarCheck /></div><span className="text-xl font-bold text-white">ATRIO</span></div><div><p className="max-w-lg text-5xl font-bold leading-tight text-white">Better attendance starts with a clearer picture.</p><p className="mt-5 max-w-md text-slate-400">The calm, connected workspace for teachers and administrators at Zynthra Technologies.</p></div><p className="text-sm text-slate-500">© 2026 Zynthra Technologies</p></div><div className="flex items-center justify-center p-5 sm:p-10"><form onSubmit={submit} className="glass w-full max-w-md rounded-3xl p-7 sm:p-9"><div className="mb-7 lg:hidden"><div className="flex items-center gap-2 font-bold text-white"><CalendarCheck className="text-indigo-400" />ATRIO</div></div><p className="text-sm font-medium text-indigo-300">WELCOME BACK</p><h1 className="mt-2 text-3xl font-bold text-white">Sign in to your workspace</h1><p className="mt-2 text-sm text-slate-400">Choose your role and enter your details.</p><div className="mt-6 grid grid-cols-2 rounded-xl bg-slate-950/50 p-1">{(['Admin', 'Teacher'] as const).map(item => <button type="button" key={item} onClick={() => setRole(item)} className={`rounded-lg py-2 text-sm font-medium transition ${role === item ? 'bg-indigo-500 text-white shadow' : 'text-slate-400'}`}>{item}</button>)}</div><label className="mt-5 block text-sm text-slate-300">Email<div className="relative mt-2"><Mail className="absolute left-3 top-3 text-slate-500" size={17} /><input className="field pl-10" type="email" value={email} onChange={e => setEmail(e.target.value)} required /></div></label><label className="mt-4 block text-sm text-slate-300">Password<div className="relative mt-2"><LockKeyhole className="absolute left-3 top-3 text-slate-500" size={17} /><input className="field pl-10" type="password" placeholder="••••••••" value={password} onChange={e => setPassword(e.target.value)} required /></div></label>{error && <p className="mt-3 text-sm text-rose-300">{error}</p>}<button disabled={submitting} className="btn-primary mt-6 w-full">{submitting ? 'Signing in...' : `Sign in as ${role}`}</button><p className="mt-4 text-center text-xs text-slate-500">Use the seeded account: admin@atrio.com</p></form></div></div>
}
